module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bgray: "var(--bgray)",
        black: "var(--black)",
        "carbon-darkest": "var(--carbon-darkest)",
        "carbon-neutral300": "var(--carbon-neutral300)",
        codingpurple: "var(--codingpurple)",
        codingyellow: "var(--codingyellow)",
        "defaultsystemgray-0-2dark": "var(--defaultsystemgray-0-2dark)",
        "gray-1": "var(--gray-1)",
        "gray-3": "var(--gray-3)",
        "gray-4": "var(--gray-4)",
        "gray-5": "var(--gray-5)",
        "gray-6": "var(--gray-6)",
        "gridlight-grey": "var(--gridlight-grey)",
        "label-colordarkprimary": "var(--label-colordarkprimary)",
        "label-colorlightprimary": "var(--label-colorlightprimary)",
        "main-black": "var(--main-black)",
        "neutral-colors100": "var(--neutral-colors100)",
        "neutral-colors300": "var(--neutral-colors300)",
        "neutral-colors400": "var(--neutral-colors400)",
        "neutral-colors500": "var(--neutral-colors500)",
        "neutral-colors700": "var(--neutral-colors700)",
        "primary-colorscolor-1": "var(--primary-colorscolor-1)",
        text: "var(--text)",
        textgrey: "var(--textgrey)",
        unseected: "var(--unseected)",
        white: "var(--white)",
        "white-1": "var(--white-1)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        body: "var(--body-font-family)",
        "body-bold": "var(--body-bold-font-family)",
        "body-regular": "var(--body-regular-font-family)",
        "caption1-regular": "var(--caption1-regular-font-family)",
        "caption2-regular": "var(--caption2-regular-font-family)",
        "default-regular-callout": "var(--default-regular-callout-font-family)",
        "default-regular-footnote":
          "var(--default-regular-footnote-font-family)",
        "footnote-bold": "var(--footnote-bold-font-family)",
        "footnote-regular": "var(--footnote-regular-font-family)",
        name: "var(--name-font-family)",
        "paragraph-small": "var(--paragraph-small-font-family)",
        "subheadline-bold": "var(--subheadline-bold-font-family)",
        "subheadline-regular": "var(--subheadline-regular-font-family)",
        "text-single-100-medium": "var(--text-single-100-medium-font-family)",
        "text-single-200-medium": "var(--text-single-200-medium-font-family)",
        "text-single-300-medium": "var(--text-single-300-medium-font-family)",
        "title2-regular": "var(--title2-regular-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "general-shadow-01": "var(--general-shadow-01)",
        "general-shadow-02": "var(--general-shadow-02)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
