export const fetchCHWs = async () => {
  const mockData = [
    {
      id: 1,
      full_name: "Uwase Marie Claire",
      gender: "Female",
      phone_number: "+250733333333",
      location: "Kimironko / Biryogo",
      start_date: "25 - 09 - 2025",
      status: "Active",
    },
    {
      id: 2,
      full_name: "Mugisha Jean Paul",
      gender: "Male",
      phone_number: "+250788888888",
      location: "Remera / Gisozi",
      start_date: "15 - 08 - 2025",
      status: "Active",
    },
    {
      id: 3,
      full_name: "Umutoni Grace",
      gender: "Female",
      phone_number: "+250722222222",
      location: "Kicukiro / Niboye",
      start_date: "10 - 07 - 2025",
      status: "Active",
    },
    {
      id: 4,
      full_name: "Niyonzima Patrick",
      gender: "Male",
      phone_number: "+250799999999",
      location: "Nyarugenge / Nyamirambo",
      start_date: "20 - 06 - 2025",
      status: "Inactive",
    },
    {
      id: 5,
      full_name: "Mukamana Sarah",
      gender: "Female",
      phone_number: "+250711111111",
      location: "Gasabo / Kinyinya",
      start_date: "05 - 05 - 2025",
      status: "Active",
    },
    {
      id: 6,
      full_name: "Habimana David",
      gender: "Male",
      phone_number: "+250744444444",
      location: "Kimironko / Gikondo",
      start_date: "12 - 04 - 2025",
      status: "Active",
    },
    {
      id: 7,
      full_name: "Kamanzi Alice",
      gender: "Female",
      phone_number: "+250755555555",
      location: "Remera / Rusororo",
      start_date: "18 - 03 - 2025",
      status: "Active",
    },
    {
      id: 8,
      full_name: "Bizimana Eric",
      gender: "Male",
      phone_number: "+250766666666",
      location: "Kicukiro / Kanombe",
      start_date: "22 - 02 - 2025",
      status: "Inactive",
    },
    {
      id: 9,
      full_name: "Nyirahabimana Jane",
      gender: "Female",
      phone_number: "+250777777777",
      location: "Nyarugenge / Muhima",
      start_date: "30 - 01 - 2025",
      status: "Active",
    },
    {
      id: 10,
      full_name: "Ndayambaje Robert",
      gender: "Male",
      phone_number: "+250733333334",
      location: "Gasabo / Jabana",
      start_date: "15 - 12 - 2024",
      status: "Active",
    },
  ];

  return Promise.resolve(mockData);
};
